apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-svc"
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - targetPort: {{ .Values.port }}
      port: {{ .Values.port }}
      protocol: TCP